version: '3.8'

services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - PORT=3000
      - NODE_ID=node1
    networks:
      - kv-network
    deploy:
      replicas: 1

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3001:3000"
    environment:
      - PORT=3000
      - NODE_ID=node2
    networks:
      - kv-network
    deploy:
      replicas: 1

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3002:3000"
    environment:
      - PORT=3000
      - NODE_ID=node3
    networks:
      - kv-network
    deploy:
      replicas: 1

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    depends_on:
      - node1
      - node2
      - node3
    networks:
      - kv-network
    tty: true
    stdin_open: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8080:80"
    depends_on:
      - node1
      - node2
      - node3
    networks:
      - kv-network

networks:
  kv-network:
    driver: bridge
